### ISSUE TITLE
Observed Trade Route event at 19:52 (UTC) instead of Condor Egg

### ISSUE THREAD

**Issue by ghost-90** [richardwestenra/rdr2-free-roam-event-schedule#17]
Hello, instead of Condor Egg, at 21:52 (CEST [19:52 (UTC)]) I participated in Trade route.
By the way, could you share latest meta on trade route? I was googling and found only years old info that it is supposed to repeat every 6 hours, then some rumors that it changed in the meanwhile.
I checked the spreadsheet and came to conclusion that it happens at 6:22, 10:52, 19:52 UTC. Please correct me if I'm wrong.
Thanks for looking into this.
Best regards
Ghost-90

**Comment by richardwestenra** [comment]
Hi @ghost-90, thanks for this. The schedule will have updated since you posted this comment. The schedule is now pulling live event data from api.rdo.gg as its source, so it should stay much more up to date. Thanks!

Also I've no idea about gameplay meta, I haven't played RDO for a couple years now.

**Comment by ghost-90** [comment]
Thanks, bro! :) Huge improvement pulling from RDO Compendium as source. :) Yay!
