### ISSUE TITLE
Breaks at midnight.

### ISSUE THREAD

**Issue by Senexis** [richardwestenra/rdr2-free-roam-event-schedule#4]
Heya, great app!

Just wanted to leave a quick note to let you know that the site breaks at midnight. Specifically at the 0th hour. Once the clock ticks over to the 1st hour it seems to work again just fine. I've tested this at both +0000 and +0200 so far, and it seems to break at the 0th hour for both.

When this issue occurs, no event will be displayed as "next up", nor will the "in X minutes" text be filled properly. After a little experimenting, it seems that the `eta` property is way too long for events that you'd think would be close to "now". My suspicion is that it has something todo with the "timezone bug fix" that adds a day to the `eta` property.

Thanks for the app, it's been useful so far. Hope you can get this issue worked out!

**Comment by richardwestenra** [comment]
ooh good catch, thanks! I'll check it out

**Comment by richardwestenra** [comment]
@Senexis Hey I'm struggling to replicate this, except at `00:00:00.000` (where it does fail, but that's because it's checking for `eta > 0 && eta < frequency` instead of `eta > 0 && eta <= frequency` - which I should change, but I don't think it's a big deal, because it only applies for a millisecond so you'd have to be very unlucky to catch it).

Can you please clarify, are you talking about it only breaking on the instant of midnight, or for the entire hour of 00:00 to 01:00? If so, what time-zone are you in?

**Comment by Senexis** [comment]
Sure. It seems to break between 0000 and 0100. I'm in CEST (GMT +2), and for the entire hour it does not get filled with the next event. For further information, it breaks in Chrome, Edge and in Node, it seems.

If you can't replicate it, I'll try to catch it in the act again. The last time I've noticed this was last Saturday.

**Comment by richardwestenra** [comment]
Gotcha, I see. Wasn't able to get it working in my time zone (GMT/BST) but I've replicated it now that I've changed my computer time zone to CEST. Thanks!

**Comment by richardwestenra** [comment]
This should be fixed now hopefully. Let me know how you get on, and thanks for the detailed report!
